name: "Scheduled File Creation and Push"

on:
  schedule:
    # Schedule: 8 AM, 11 AM, 2 PM, 5 PM, and 8 PM UTC
    - cron: "0 8,11,14,17,19,20,22,24 * * *"
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated from v2 to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated from v2 to v3
        with:
          node-version: "20"  # Specify the latest Node.js version to use

      - name: Install dependencies
        run: npm install

      - name: Run the automation script
        run: node automatedCommit.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name imankii01
          git config --global user.email private.ankit047@gmail.com
          git pull origin main
          git add .
          git commit -m "Automated commit with random content"
          git push origin main 
