name: "Scheduled File Creation and Push"

on:
  schedule:
    - cron: "0 8,11,14,17,20 * * *"
  workflow_dispatch: 

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run the automation script
        run: node automatedCommit.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name imankii01
          git config --global user.email private.ankit047@gmail.com
          git add .
          git commit -m "Automated commit with random content"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
